package com.example.backend.repositories;

import com.example.backend.models.Message;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DataMongoTest
class MessageRepositoryIntegrationTest {

    @Autowired
    private MessageRepository messageRepository;

    @BeforeEach
    void cleanDatabase() {
        messageRepository.deleteAll();
    }

    @Test
    void testSaveAndFindById() {
        Message message = new Message("Hello MongoDB!");
        Message saved = messageRepository.save(message);

        assertNotNull(saved.getId(), "Saved message should have an autogenerated ID");

        Optional<Message> found = messageRepository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals("Hello MongoDB!", found.get().getContent());
    }

    @Test
    void testFindAllReturnsAllMessages() {
        messageRepository.save(new Message("One"));
        messageRepository.save(new Message("Two"));

        assertEquals(2, messageRepository.findAll().size());
    }

    @Test
    void testDeleteMessage() {
        Message msg = messageRepository.save(new Message("To be deleted"));

        messageRepository.deleteById(msg.getId());

        Optional<Message> result = messageRepository.findById(msg.getId());
        assertTrue(result.isEmpty(), "Message should be deleted");
    }
}
